include:
  - board: nice_nano//zmk
    shield: corne_central_dongle rgbled_adapter
  - board: nice_nano//zmk
    shield: corne_peripheral_left
  - board: nice_nano//zmk
    shield: corne_peripheral_right
  - board: nice_nano//zmk
    shield: settings_reset
