CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Led indicator
CONFIG_INDICATOR_LED_WIDGET=y

CONFIG_INDICATOR_LED_BATTERY_LEVEL_HIGH=20      
CONFIG_INDICATOR_LED_BATTERY_LEVEL_CRITICAL=19  

CONFIG_INDICATOR_LED_BATTERY_HIGH_BLINK_REPEAT=2
CONFIG_INDICATOR_LED_INTERVAL_MS=400

CONFIG_INDICATOR_LED_BATTERY_CRITICAL_BLINK_REPEAT=5
CONFIG_INDICATOR_LED_INTERVAL_MS=150
